#lang racket
(require "sprites.rkt")

(struct Piece [name isWhite sprite])
(define emptyCell 'null)


(define boardVector
  (vector-immutable 
  (vector-immutable (Piece "rook" #f BLACK-ROOK) (Piece "knight" #f BLACK-KNIGHT) (Piece "bishop" #f BLACK-BISHOP) (Piece "queen" #f BLACK-QUEEN) (Piece "king" #f BLACK-KING) (Piece "bishop" #f BLACK-BISHOP) (Piece "knight" #f BLACK-KNIGHT) (Piece "rook" #f BLACK-ROOK))
  (vector-immutable (Piece "pawn" #f BLACK-PAWN) (Piece "pawn" #f BLACK-PAWN) (Piece "pawn" #f BLACK-PAWN) (Piece "pawn" #f BLACK-PAWN) (Piece "pawn" #f BLACK-PAWN) (Piece "pawn" #f BLACK-PAWN) (Piece "pawn" #f BLACK-PAWN) (Piece "pawn" #f BLACK-PAWN))
  (vector-immutable emptyCell emptyCell emptyCell emptyCell emptyCell emptyCell emptyCell emptyCell)
  (vector-immutable emptyCell emptyCell emptyCell emptyCell emptyCell emptyCell emptyCell emptyCell)
  (vector-immutable emptyCell emptyCell emptyCell emptyCell emptyCell emptyCell emptyCell emptyCell)
  (vector-immutable emptyCell emptyCell emptyCell emptyCell emptyCell emptyCell emptyCell emptyCell)
  (vector-immutable (Piece "pawn" #t WHITE-PAWN) (Piece "pawn" #t WHITE-PAWN) (Piece "pawn" #t WHITE-PAWN) (Piece "pawn" #t WHITE-PAWN) (Piece "pawn" #t WHITE-PAWN) (Piece "pawn" #t WHITE-PAWN) (Piece "pawn" #t WHITE-PAWN) (Piece "pawn" #t WHITE-PAWN))
  (vector-immutable (Piece "rook" #t WHITE-ROOK) (Piece "knight" #t WHITE-KNIGHT) (Piece "bishop" #t WHITE-BISHOP) (Piece "queen" #t WHITE-QUEEN) (Piece "king" #t WHITE-KING) (Piece "bishop" #t WHITE-BISHOP) (Piece "knight" #t WHITE-KNIGHT) (Piece "rook" #t WHITE-ROOK))
  ))
(struct WS[board firstClick firstCoord isWhiteTurn])
(define(set-board ws board)
  (WS board))
(define(set-name name piece)
  (Piece name (Piece-isWhite piece) (Piece-sprite piece)))
(define(set-isWhite isWhite piece)
  (Piece (Piece-name piece) isWhite (Piece-sprite piece)))
(define(set-sprite sprite piece)
  (Piece (Piece-name piece) (Piece-isWhite piece) sprite))
(provide Piece)
(provide Piece-name)
(provide Piece-isWhite)
(provide Piece-sprite)
(provide boardVector)
(provide WS)
(provide WS-board)
(provide WS-firstClick)
(provide WS-firstCoord)
(provide WS-isWhiteTurn)
(provide set-board)
(provide set-name)
(provide set-isWhite)
(provide set-sprite)

