#lang racket
(require 2htdp/image)

(define LIGHT-SQUARE (bitmap "img/square brown dark_png_128px.png"))
(define DARK-SQUARE (bitmap "img/square brown light_png_128px.png"))
(define WHITE-PAWN (bitmap "img/w_pawn_png_128px.png"))
(define BLACK-PAWN (bitmap "img/b_pawn_png_128px.png"))
(define WHITE-ROOK (bitmap "img/w_rook_png_128px.png"))
(define BLACK-ROOK (bitmap "img/b_rook_png_128px.png"))
(define WHITE-KNIGHT (bitmap "img/w_knight_png_128px.png"))
(define BLACK-KNIGHT (bitmap "img/b_knight_png_128px.png"))
(define WHITE-BISHOP (bitmap "img/w_bishop_png_128px.png"))
(define BLACK-BISHOP (bitmap "img/b_bishop_png_128px.png"))
(define WHITE-QUEEN (bitmap "img/w_queen_png_128px.png"))
(define BLACK-QUEEN (bitmap "img/b_queen_png_128px.png"))
(define WHITE-KING (bitmap "img/w_king_png_128px.png"))
(define BLACK-KING (bitmap "img/b_king_png_128px.png"))
(define BUTTON-BLACK (scale .2 (bitmap "Forfeit-black.png")))
(define BUTTON-WHITE (scale .2 (bitmap "Forfeit-white.png")))
(define BLACK-WINS (bitmap "img/BLACK-WINS.png"))
(define WHITE-WINS (bitmap "img/WHITE-WINS.png"))
(provide LIGHT-SQUARE)
(provide DARK-SQUARE)
(provide WHITE-PAWN)
(provide BLACK-PAWN)
(provide WHITE-ROOK)
(provide BLACK-ROOK)
(provide WHITE-KNIGHT)
(provide BLACK-KNIGHT)
(provide WHITE-BISHOP)
(provide BLACK-BISHOP)
(provide WHITE-QUEEN)
(provide BLACK-QUEEN)
(provide WHITE-KING)
(provide BLACK-KING)
(provide BUTTON-WHITE)
(provide BUTTON-BLACK)
(provide WHITE-WINS)
(provide BLACK-WINS)